import 'package:flutter_bloc/flutter_bloc.dart';
import '../../models/user_model.dart';
import '../../services/auth_service.dart';
import 'auth_event.dart';
import 'auth_state.dart';

export 'auth_event.dart';
export 'auth_state.dart';

class AuthBloc extends Bloc<AuthEvent, AuthState> {
  final AuthService _authService;

  AuthBloc({required AuthService authService}) 
      : _authService = authService,
        super(AuthInitial()) {
          
    on<LoginRequested>((event, emit) async {
      emit(AuthLoading());
      
      try {
        final result = await _authService.login(event.email, event.password);
        
        if (result['success']) {
          // You might want to parse the user name from result['data'] if available
          emit(Authenticated(event.email));
        } else {
          emit(AuthError(result['message'] ?? 'Login failed'));
        }
      } catch (e) {
        emit(AuthError('An error occurred during login'));
      }
    });

    on<RegisterRequested>((event, emit) async {
      emit(AuthLoading());
      
      try {
        final user = UserModel(
          id: '', // ID will be generated by backend
          name: event.name,
          rollNo: event.rollNo,
          branch: event.branch,
          year: event.year,
          program: event.program,
          email: event.email,
          role: 'member',
        );

        final result = await _authService.registerStudent(user, event.password);
        
        if (result['success']) {
          emit(RegisterSuccess(event.email));
        } else {
          emit(AuthError(result['message'] ?? 'Registration failed'));
        }
      } catch (e) {
        emit(AuthError('An error occurred during registration: $e'));
      }
    });

    on<LogoutRequested>((event, emit) async {
      emit(AuthLoading());
      await _authService.logout();
      emit(Unauthenticated());
    });

    on<ForgotPasswordRequested>((event, emit) async {
      emit(AuthLoading());
      try {
        // App uses rollNo or email for this field. Passing it to the service.
        final result = await _authService.forgotPassword(event.rollNo);
        if (result['success']) {
          emit(AuthForgotPasswordOtpSent());
        } else {
          emit(AuthError(result['message'] ?? 'Failed to send OTP'));
        }
      } catch (e) {
        emit(AuthError('An error occurred'));
      }
    });

    on<OtpVerificationRequested>((event, emit) async {
      emit(AuthLoading());
      // In a real flow, OTP verification might happen on the backend, 
      // or the OTP is used as the token for resetting the password.
      // We will assume local validation or passing to the next step.
      await Future.delayed(const Duration(milliseconds: 500));
      if (event.otp.length >= 4) { 
        emit(AuthForgotPasswordVerified());
      } else {
        emit(const AuthError("Invalid OTP"));
      }
    });

    on<ResetPasswordRequested>((event, emit) async {
      emit(AuthLoading());
      try {
        // We assume the token/OTP was verified and we are resetting.
        // We might need to store the token from OtpVerificationRequested,
        // but for now we pass a placeholder or the last used OTP.
        // If the backend requires a specific token, we need to adjust the flow.
        final result = await _authService.resetPassword('TOKEN_PLACEHOLDER', event.newPassword);
        
        if (result['success']) {
          emit(AuthPasswordResetSuccess());
        } else {
          emit(AuthError(result['message'] ?? 'Failed to reset password'));
        }
      } catch (e) {
        emit(AuthError('An error occurred'));
      }
    });
  }
}
